</section>
<!--Footer-->
<?php $this->get_part('footer'); ?>

<!-- Cookie-Alert -->
<div class="cookie-alert">
    <div class="page-card">
        <div class="card-row">
            <div class="card-col cookie-col center">
                <a href="https://autoriteitpersoonsgegevens.nl/nl/onderwerpen/internet-telefoon-tv-en-post/cookies" target="_blank" class="cookie-icon">
                    <i class="fas fa-cookie-bite"></i>
                </a>
            </div>
            <div class="card-col">
                <div class="cookie-text">Wij gebruiken cookies op deze pagina voor uw gemak, wij verzamelen geen data.</div>
            </div>
            <div class="card-col close-col center">
                <div class="close-icon">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!--JS-->
<?php require_once JS; ?>

</body>
</html>