<!doctype html>

<!--[if IE]>
<?= require_once ERROR_UNSUPPORTED ?>
<![endif]-->

<html lang="en">
<head>
    <!--Define url-->
    <script>window.app = {baseUrl: <?php print json_encode($this->urlArr['baseUrl']); ?> };</script>

    <!--Page Title-->
    <title><?= PAGENAME ?></title>

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="<?= PageController::url('img/favicon/apple-touch-icon.png') ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= PageController::url('img/favicon/favicon-32x32.png') ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= PageController::url('img/favicon/favicon-16x16.png') ?>">
    <link rel="manifest" href="<?= PageController::url('img/favicon/site.webmanifest') ?>">
    <link rel="mask-icon" href="<?= PageController::url('img/favicon/safari-pinned-tab.svg') ?>" color="#5bbad5">
    <!--For the favicons I recommend using https://realfavicongenerator.net/, this will give you all the icons for every browser.-->

    <!--Meta and CSS-->
    <?php
    require_once META;
    require_once CSS;
    ?>
</head>
<body>
<!-- Loading icon -->
<div id="load">
    <div class="center" id="load-img"><?= ApplicationController::load_svg('logo') ?></div>
</div>

<!--Navbar-->
<?php
if ($this->urlArr['pagename'] != 'login') {
    if (isset($_SESSION["user_role"])) {
        $this->get_part('navbar');
    } else {
        if ($this->urlArr['pagename'] != 'logout') {
            require_once ERROR_403_PAGE;
            header("Refresh: 2; url=" . PageController::url('login') . "");
        }
    }
}
?>

<!--Content-->
<section class="content" id="content">