<!--Set Charset-->
<meta charset="utf-8">

<!--IE Support-->
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">

<!--Set Viewport-->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--Description-->
<meta name="description" content="ETWS.nl is voor mensen met een ETWS, slim grijs water systeem!">

<!--Theme color-->
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="theme-color" content="#ffffff">