<div class="page dashboard" id="display">
    <div class="page-row">
        <div class="page-col">
            <div class="page-row dash-day">
                <div class="page-col">
                    <div class="page-card">
                        <div class="card-row">
                            <div class="card-col">
                                <h1 class="card-head">Vandaag:</h1>
                            </div>
                            <div class="card-col col-reload col-right">
                                <div class="reload">
                                    <span class="reload-text">Ophalen...</span>
                                    <i class="fas fa-sync-alt" id="reload"></i>
                                </div>
                            </div>
                        </div>
                        <div class="card-table table-today">
                            <div class="table-row">
                                <div class="table-col col-xlarge center"><?= DashboardPage::getDayKilowatt(DATE) ?></div>
                            </div>
                            <div class="table-row">
                                <div class="table-col col-medium center"><?= DashboardPage::calcDayEuro() ?></div>
                            </div>
                            <div class="table-row row-text">
                                <div class="table-col col-small col-text center"><?= DashboardPage::getDayText() ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-row">
                <div class="page-col">
                    <div class="page-card">
                        <h1 class="card-head">Deze maand:</h1>
                        <div class="card-table table-month">
                            <div class="table-row">
                                <div class="table-col col-large center"><?= DashboardPage::calcMonthKilowattTotal() . " kWh" ?></div>
                            </div>
                            <div class="table-row">
                                <div class="table-col col-small center"><?= "&plusmn; € " . number_format(DashboardPage::calcMonthKilowattTotal() * COST, 2) ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="page-col">
                    <div class="page-card">
                        <h1 class="card-head">Totaal:</h1>
                        <div class="card-table table-total">
                            <div class="table-row">
                                <div class="table-col col-large center"><?= DashboardPage::calcKilowattTotal() . " kWh" ?></div>
                            </div>
                            <div class="table-row">
                                <div class="table-col col-small center"><?= "&plusmn; € " . number_format(DashboardPage::calcKilowattTotal() * COST, 2) ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-col">
            <div class="page-card">
                <div class="card-row">
                    <div class="card-col">
                        <h1 class="card-head">Deze Week:</h1>
                    </div>
                    <div class="card-col col-right">
                        <div class="product-text">Opgehaald: <?= TIME_FULL ?></div>
                    </div>
                </div>
                <div class="card-table table-week">
                    <div class="table-row table-head">
                        <div class="table-col first-col">Dag:</div>
                        <div class="table-col">Opgewekt (kWh):</div>
                        <div class="table-col">Bespaard (€):</div>
                    </div>
                    <div class="table-row row-hover striped" id="mon">
                        <div class="table-col first-col">Maandag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(0)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover" id="tue">
                        <div class="table-col first-col">Dinsdag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(1)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover striped" id="wed">
                        <div class="table-col first-col">Woensdag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(2)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover" id="thu">
                        <div class="table-col first-col">Donderdag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(3)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover striped" id="fri">
                        <div class="table-col first-col">Vrijdag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(4)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover" id="sat">
                        <div class="table-col first-col">Zaterdag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(5)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <div class="table-row row-hover striped" id="sun">
                        <div class="table-col first-col">Zondag</div>
                        <div class="table-col"><?= DashboardPage::getWeekKilowatt(DashboardPage::selectWeekDate(6)) ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuro() ?></div>
                    </div>
                    <hr class="divide-hr">
                    <div class="table-row table-head">
                        <div class="table-col first-col">Totaal:</div>
                        <div class="table-col"><?= DashboardPage::calcWeekKilowattTotal() ?></div>
                        <div class="table-col"><?= DashboardPage::calcWeekEuroTotal() ?></div>
                    </div>
                    <div class="table-row table-legend">
                        <div class="table-col">1 kWh is <?= COST ?> euro</div>
                        <div class="table-col col-right">"-" = geen data beschikbaar</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>