<div class="page help">
    <div class="page-row">
        <div class="page-col">
            <div class="page-card">
                <div class="page-row">
                    <div class="page-col col-left">
                        <h1 class="card-head">FAQ:</h1>
                        <div class="card-row question-row">
                            <div class="question striped">
                                <h1 class="question-head">Q:</h1>
                                <h3 class="question-text">Wat moet ik doen als mijn systeem niet meer werkt?</h3>
                                <h1 class="question-head">A:</h1>
                                <h3 class="question-text">Als dit het geval is moet u contact opnemen met ons, wij sturen dan zo spoedig mogelijk een monteur naar u toe!</h3>
                            </div>
                            <div class="question striped">
                                <h1 class="question-head">Q:</h1>
                                <h3 class="question-text">Hoe kan ik zien of het systeem aanstaat? Want er staat dat er niets is opgewekt.</h3>
                                <h1 class="question-head">A:</h1>
                                <h3 class="question-text">Door op het apparaat te kijken kunt u een status lamp vinden, als deze aanstaat is het apparaat werkend.
                                                          Het kan zijn dat er toevallig nog niets is opgewekt. Mocht dit probleem blijven bestaan, neem dan contact met ons op.</h3>
                            </div>
                            <div class="question striped last">
                                <h1 class="question-head">Q:</h1>
                                <h3 class="question-text">Wat moet ik doen als het apparaat een melding geeft dat hij verstopt zit? Help!</h3>
                                <h1 class="question-head">A:</h1>
                                <h3 class="question-text">Zorg dat eventuele kranen en andere grijswater sanitair uit staat en schakel het systeem uit via de knop aan de achterkant.
                                                          Vervolgens zult u het apparaat moeten openen via de klep aan de voorkant en de verstopping verwijderen.
                                                          Lukt dit niet of is het probleem niet opgelost, neem dan contact op met ons en wij zullen u passend verder assisteren.</h3>
                            </div>
                        </div>
                    </div>
                    <hr class="divide-vr">
                    <div class="page-col col-right">
                        <div class="page-row">
                            <div class="page-col">
                                <h1 class="card-head">Contact:</h1>
                                <div class="card-table table-info">
                                    <div class="table-row contact-row">
                                        <div class="table-col">Tel:</div>
                                        <div class="table-col">
                                            <a class="table-link" href="tel:0881234567">088 - 123 45 67</a>
                                        </div>
                                    </div>
                                    <div class="table-row contact-row">
                                        <div class="table-col">E-Mail:</div>
                                        <div class="table-col">
                                            <a class="table-link" href="mailto:support@etws.nl">support@etws.nl</a>
                                        </div>
                                    </div>
                                    <div class="table-row contact-row">
                                        <div class="table-col">KvK:</div>
                                        <div class="table-col">12345678</div>
                                    </div>
                                    <div class="table-row contact-row">
                                        <div class="table-col">Adres:</div>
                                        <div class="table-col">Veenkade 157,<br>2513 EL Den Haag</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="page-row">
                            <div class="page-col">
                                <h1 class="card-head">Locatie:</h1>
                                <iframe class="info-map" src="https://maps.google.com/maps?width=100%25&amp;height=400&amp;hl=nl&amp;q=Veenkade%20157,%202513%20EL%20Den%20Haag+(ETWS)&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>